#!/usr/bin/env ruby

require 'thor'

module FMSAdmin

  class CLI < Thor

    desc "list", "Lists the names of all applications installed"
    method_option :force, :aliases => "-f", :type => :boolean, :default => false, :desc => "Forces a refresh of the cached list of applications"
    method_option :verbose, :aliases => "-v", :type => :boolean, :default => true, :desc => "true displays all the applications under a virtual host; false displays the total number of applications"
    def list
      puts "list #{options.inspect}"
    end

    desc "add", "Adds a new application to the virtual host you are connected to by creating the required directory for the new application in the directory tree"
    method_option :app, :aliases => "-a", :required => true, :desc => "The name of the application to be added."
    def add
      puts "add #{options.inspect}"
    end

    desc "remove", "remove application"
    method_option :apps, :aliases => "-a", :desc => "application(s) name(s) to add"
    def remove
      puts "remove #{options.inspect}"
    end

    desc "reload",  "Shuts down an instance of the application, if running, and reloads it"
    method_option :app, :aliases => "-a", :required => true, :desc => "The name of the application or instance of the application, in the form: application_name[/instance_name]"
    def reload
      puts "reload #{options.inspect}"
    end

    desc "unload", "Shuts down all instances of the specified application or instance of an application"
    method_option :app, :aliases => "-a", :required => true, :desc => "The name of the application or instance of the application, in the form: application_name[/instance_name]"
    def unload
      puts "unload #{options.inspect}"
    end
  end

end

FMSAdmin::CLI.start
