#!/usr/bin/env ruby

require 'thor'
require 'thor/group'

module FMSAdmin
  module Command

    class App < Thor

      def self.auth_options
        method_option :user, :aliases => "-u", :required => true
        method_option :password, :aliases => "-p", :required => true
      end

      def self.app_name_option(desc = nil)
        desc ||= "The name of the application or instance of the application, in the form: application_name[/instance_name]"
        method_option :app, :aliases => "-a", :required => true, :desc => desc
      end

      desc "list", "Lists the names of all installed applications"
      auth_options
      method_option :force, :aliases => "-f", :type => :boolean, :default => false, :desc => "Forces a refresh of the cached list of applications"
      method_option :verbose, :aliases => "-v", :type => :boolean, :default => true, :desc => "true displays all the applications under a virtual host; false displays the total number of applications"
      def list
        puts "list #{options.inspect}"
      end

      desc "add", "Adds a new application to the virtual host you are connected to by creating the required directory for the new application in the directory tree"
      auth_options
      app_name_option "The name of the application to be added."
      def add
        puts "add #{options.inspect}"
      end

      desc "remove", "remove application"
      auth_options
      app_name_option
      def remove
        puts "remove #{options.inspect}"
      end

      desc "reload",  "Shuts down an instance of the application, if running, and reloads it"
      auth_options
      app_name_option
      def reload
        puts "reload #{options.inspect}"
      end

      desc "unload", "Shuts down all instances of the specified application or instance of an application"
      auth_options
      app_name_option
      def unload
        puts "unload #{options.inspect}"
      end

      protected

      def self.basename
        super + ' app'
      end
      
    end

  end
end

module FMSAdmin

  class CLI < Thor

    register FMSAdmin::Command::App, :app, "app", "Manager applications and instances"

  end

end

FMSAdmin::CLI.start
